### ISSUE TITLE
MACCS Possibility to run for a small Region of Interest

### ISSUE THREAD

**Issue by WOTR-VJ** [Sen2Agri/Sen2Agri-System#17]
Is it possible to feed bounding coordinates in MACCS so the small area in the tile can be processed

**Comment by lnicola** [comment]
No, it only works on tiles.

**Comment by WOTR-VJ** [comment]
Okay. Could you please share the example shapefiles related to input In-situ data and Strata in L4 processor

**Comment by lnicola** [comment]
I'm not sure I can do that, since the data doesn't belong to us. I can try to ask around, but these days we're pretty much swamped.

**Comment by WOTR-VJ** [comment]
No problem even the template files without data will also help. See what is possible and thanks in advance

**Comment by lnicola** [comment]
If you have some shapefiles, I can take a look. Basically, the site can be a single polygon, the attributes (fields) don't matter. For the in-situ data you need a `CODE` attribute with the crop class (it should be numeric) and a `CROP` attribute that's 0 for non-crop classes and 1 for crop classes.

**Comment by WOTR-VJ** [comment]
Okay, this details will help me to create the shapefile. Thanks

**Comment by vijay-spatial** [comment]
Hi Incola
I am trying to run the CropMask.py and I am getting the following error
Main mission: SENTINEL
Tiles: 1
43QDB 5
Single stratum: False
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sen2agri_common.py", line 539, in execute
    self.load_tiles()
  File "/usr/lib/python2.7/site-packages/sen2agri_common.py", line 783, in load_tiles
    self.strata = load_strata(self.args.filtered_strata, self.site_footprint_wgs84)
  File "/usr/lib/python2.7/site-packages/sen2agri_common.py", line 382, in load_strata
    raise Exception("Could not open stratum dataset", areas)
Exception: ('Could not open stratum dataset', '/mnt/data/archive/insitu/sangamner/Sangamner_p.shp')
Processor finished in 0:00:00.055471
Strata I have given here is the site polygon
Projection UTM/WGS84

Could you please help me to rectify this error
Thanks
Vijay
