### ISSUE TITLE
offline_l1_handler fails due to unsupported type of fake_season_start and fake_season_end

### ISSUE THREAD

**Issue by tmistelbauer** [Sen2Agri/Sen2Agri-System#4]
fake_seson_start and fake_season_end are [here](https://github.com/Sen2Agri/Sen2Agri-System/blob/master/sen2agri-downloaders/offline_l1_handler.py#L60) defined as "MMDD" datestring. Hoewever, this leads to the following error:

```
./offline_l1_handler.py -d /home/sen2agri/testproducts/ -s waldviertelTraceback (most recent call last):
  File "./offline_l1_handler.py", line 67, in <module>
    sentinel_aoi_contexts_aoi_database = sentinel_db_info.getSentinelAOI(-1, fake_season_start, fake_season_end)
  File "/usr/lib/python2.7/site-packages/sen2agri_common_db.py", line 1139, in getSentinelAOI
    return self.getAOINew(SENTINEL2_SATELLITE_ID, site_id, start_date, end_date)
  File "/usr/lib/python2.7/site-packages/sen2agri_common_db.py", line 896, in getAOINew
    currentSeasonInfo.setStartSeasonDate(start_date)
  File "/usr/lib/python2.7/site-packages/sen2agri_common_db.py", line 521, in setStartSeasonDate
    self.startSeasonDate = startSeasonDate + relativedelta(months=-self.startOfSeasonOffset)
  File "/usr/lib/python2.7/site-packages/dateutil/relativedelta.py", line 247, in __radd__
    raise TypeError, "unsupported type for add operation"
TypeError: unsupported type for add operation
```
When I change the type to datetime.date (and further adapt the if statement [getAOINew](https://github.com/Sen2Agri/Sen2Agri-System/blob/master/python-libs/sen2agri_common_db.py#L892), it works.

**Comment by lnicola** [comment]
Thank you for the report. This issue should be fixed in the next version.
